### ISSUE TITLE
这个项目还在维护么？

### ISSUE THREAD

**Issue by DelightRun** [xdlinux/xdba-thesis#11]
这个项目还在维护么？另Github上还有些其他的项目正在维护

**Comment by mljli** [comment]
@DelightRun 维护基本靠每一届写论文的提pull request。据我所知，学校现在提供官方的LaTeX模板了，不知道是不是齐老师那边的。

**Comment by MiaoDX** [comment]
@mljli 嘿，你好，能给一个“官方的LaTeX模板”的链接或者类似的么？【我也依稀记得睿思上曾看到过，但当时没有在意...】（953900030@qq.com）。谢谢！

**Comment by MiaoDX** [comment]
@mljli 好像找到了 ~~ https://github.com/fredqi/xduthesis

**Comment by DelightRun** [comment]
@MiaoDX 欢迎使用https://github.com/StickCui/XDUthesis-personal， 这个我们今年新改的，比较新。

@mljli 崔元顺今年改了一个模板挺好用的，https://github.com/StickCui/XDUthesis-personal

我在考虑我们有必要把咱学校这几个模板项目整合一下做个统一的

**Comment by MiaoDX** [comment]
@DelightRun 嗯嗯，我还是先把论文写完再考虑用哪一个吧 -.-
谢啦！！ ^_^
