### ISSUE TITLE
关于Latex使用的错误

### ISSUE THREAD

**Issue by Vast-Stars** [xdlinux/xdba-thesis#12]
我用Latex编译，总是提醒
Undefined control sequence. [    \maketitle]

是不是哪里需要改设置？

**Comment by mljli** [comment]
如何编译的？请查看详细的错误信息。

另：这个项目暂时没有固定的维护人员，欢迎提供 pull request。

**Comment by Vast-Stars** [comment]
![image](https://cloud.githubusercontent.com/assets/18486331/24741883/60014d28-1ada-11e7-88de-47d95e259c91.png)
环境 TexLive 2016 各种Builder都试过了 报错都这样。是模板XDBAthesis.cfg  XDBAthesis.cls的锅。
最神奇的是，打开生成的pdf竟然是对的。。所以我正在将就着用。。
另外这个模板好像混合了本科、硕士、博士的相关格式信息呀。。感觉以后（我要是）接手的话，有种全删了重写的冲动- -

**Comment by mljli** [comment]
这个是fontspec 2.4引起的一个兼容性问题 [1]，CTEX那边已经修复了
[2]。可以选择使用包含低一点版本的fontspec的texlive，或者安装最新的CTEX包。

[1] https://github.com/CTeX-org/ctex-kit/issues/154
[2]
https://github.com/CTeX-org/ctex-kit/commit/8636eb3db04b9a03992fdbe139d37fd0f9219f9a

2017-04-06 15:07 GMT+08:00 Vast-stars <notifications@github.com>:

**Comment by mljli** [comment]
搜到一个暂时的fix，在XDBAthesis.cls里面加一行：

41a42
> \expandafter\def\csname CTEX@spaceChar\endcsname{\hspace{1em}}



2017-04-06 21:27 GMT+08:00 Minglangjun Li <liminglangjun@gmail.com>:

**Comment by mljli** [comment]
对于维护的问题，我觉得先把本科的部分做好就很好了。我毕业的时候，排版出来感觉还是有不少小问题的，另外模板很多地方也都需要根据新的改动进行更新。欢迎贡献！

2017-04-06 21:34 GMT+08:00 Minglangjun Li <liminglangjun@gmail.com>:
