### ISSUE TITLE
封面改版问题

### ISSUE THREAD

**Issue by huyangGrace** [xdlinux/xdba-thesis#5]
现在用的手册是12年出版的，封面和以前不太一样：
1.右上角的“班级”和“学号”字体也变成了宋体小四加粗。
2.填写题目、学院等的虚下划线变成了实线。

**Comment by mljli** [comment]
我和同学的对比了一下，封面确实差好多，但是手册上没有详细的排版格式，没法改

**Comment by mljli** [comment]
TODO  
* page layout 的设置有一些问题；换用 geometry 包  
* ~~封面问题（比较麻烦）~~  
* updating...
